AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  CljsTimeout:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.promise_timeout_hang_core_SLASH_promise_hang
      Runtime: nodejs4.3
      CodeUri: .
      Timeout: 5
